<!--
  About (plan §5 WP2.4, editor-core.md "About and licenses"). Owner: WP2.4.

  Version, the project license, the repository and issue addresses as text that can be
  selected and copied (the app opens no browser), a plain statement that nothing ever
  checks for updates, and the third-party notices.

  `src/lib/data/licenses.json` is 1.5 MB and is generated by `npm run licenses`, so it is
  behind a lazy `import()`: it becomes its own chunk and is fetched the first time someone
  asks for the notices, never at startup.

  Opened by `help.about` through `modals.open`, so ModalHost renders it; it is never
  mounted directly.
-->
<script module lang="ts">
  /** The repository the releases and the issue tracker live in. */
  export const REPOSITORY_URL = 'https://github.com/NC-PB/gEdit';
  /** Where to report a problem. */
  export const ISSUES_URL = `${REPOSITORY_URL}/issues`;

  /** One entry of `licenses.json`; see `scripts/gen-licenses.mjs` for the full shape. */
  export interface LicensePackage {
    name: string;
    version: string;
    license: string;
    /** 'npm' or 'cargo'. */
    source: string;
    /** Key into `texts`; several packages can share one text. */
    textId: string;
  }

  export interface LicenseData {
    packages: LicensePackage[];
    texts: Record<string, string>;
  }

  /** Stable per package, so the expanded state survives a re-render. */
  export function packageKey(pkg: LicensePackage): string {
    return `${pkg.source}:${pkg.name}@${pkg.version}`;
  }
</script>

<script lang="ts">
  import Modal from '$lib/components/common/Modal.svelte';
  import { t } from '$lib/i18n';

  interface Props {
    /** Supplied by ModalHost; the dialog only ever closes. */
    close: (value?: unknown) => void;
  }

  let { close }: Props = $props();

  type NoticeState = 'idle' | 'loading' | 'ready' | 'failed';

  let noticeState = $state<NoticeState>('idle');
  // `$state.raw`: the parsed file is ~1.5 MB and is never mutated, so it must not be proxied.
  let notices = $state.raw<LicenseData | null>(null);
  let expanded = $state<Record<string, boolean>>({});

  async function loadNotices(): Promise<void> {
    if (noticeState === 'loading' || noticeState === 'ready') return;
    noticeState = 'loading';
    try {
      const module = (await import('$lib/data/licenses.json')) as { default: unknown };
      notices = module.default as LicenseData;
      noticeState = 'ready';
    } catch (err) {
      console.error('about: the third-party notices could not be loaded', err);
      notices = null;
      noticeState = 'failed';
    }
  }

  function toggle(key: string): void {
    expanded = { ...expanded, [key]: !expanded[key] };
  }

  function sourceLabel(source: string): string {
    return source === 'cargo' ? t('help.sourceCargo') : t('help.sourceNpm');
  }

  const packages = $derived(notices?.packages ?? []);
</script>

<Modal id="about" title={t('help.aboutTitle')} hideOk cancelLabel={t('common.close')} onCancel={() => close()}>
  <div class="about">
    <p class="tagline">{t('help.tagline')}</p>

    <dl>
      <dt>{t('help.version')}</dt>
      <dd data-testid="about-version">{__APP_VERSION__}</dd>

      <dt>{t('help.license')}</dt>
      <dd data-testid="about-license">{t('help.licenseName')}</dd>

      <dt>{t('help.repository')}</dt>
      <dd><code class="address" data-testid="about-repository">{REPOSITORY_URL}</code></dd>

      <dt>{t('help.issues')}</dt>
      <dd><code class="address" data-testid="about-issues">{ISSUES_URL}</code></dd>

      <dt>{t('help.updates')}</dt>
      <dd data-testid="about-updates">{t('help.noUpdateCheck')}</dd>
    </dl>

    <p class="hint">{t('help.copyHint')}</p>

    <h3>{t('help.thirdParty')}</h3>
    {#if noticeState === 'idle'}
      <button type="button" class="link" data-testid="about-notices" onclick={loadNotices}>
        {t('help.showThirdParty')}
      </button>
    {:else if noticeState === 'loading'}
      <p class="hint" data-testid="about-notices-status">{t('help.thirdPartyLoading')}</p>
    {:else if noticeState === 'failed'}
      <p class="error" data-testid="about-notices-status">{t('help.thirdPartyFailed')}</p>
    {:else}
      <p class="hint" data-testid="about-notices-status">
        {t('help.thirdPartyIntro')}
        {t('help.packages', { count: packages.length })}
      </p>
      <div class="notices">
        {#each packages as pkg (packageKey(pkg))}
          {@const key = packageKey(pkg)}
          {@const open = Boolean(expanded[key])}
          <div class="notice" data-testid="license-entry" data-package={key} data-open={open ? '1' : '0'}>
            <button
              type="button"
              class="notice-head"
              aria-expanded={open}
              title={open ? t('help.hideLicenseText', { name: pkg.name }) : t('help.showLicenseText', { name: pkg.name })}
              onclick={() => toggle(key)}
            >
              <span class="name">{pkg.name}</span>
              <span class="version">{pkg.version}</span>
              <span class="source">{sourceLabel(pkg.source)}</span>
              <span class="spdx">{pkg.license}</span>
            </button>
            {#if open}
              <pre data-testid="license-text">{notices?.texts[pkg.textId] ?? ''}</pre>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>
</Modal>

<style>
  .about {
    display: flex;
    flex-direction: column;
    min-height: 0;
    color: var(--text-main, #cccccc);
    font-size: 13px;
  }

  .tagline {
    margin: 0 0 8px;
    color: var(--text-muted, #808080);
  }

  dl {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 3px 12px;
    margin: 0;
  }

  dt {
    color: var(--text-muted, #808080);
  }

  dd {
    margin: 0;
  }

  .address {
    font-family: var(--font-mono, monospace);
    font-size: 12px;
    user-select: text;
    cursor: text;
  }

  .hint {
    margin: 8px 0 0;
    color: var(--text-muted, #808080);
    font-size: 12px;
  }

  .error {
    margin: 8px 0 0;
    color: var(--danger-text, #f38ba8);
    font-size: 12px;
  }

  h3 {
    margin: 14px 0 6px;
    color: var(--text-active, #ffffff);
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
  }

  .link {
    align-self: flex-start;
    padding: 0;
    border: 0;
    background: transparent;
    color: var(--accent-hover, #2b88d8);
    font: inherit;
    font-size: 13px;
    text-decoration: underline;
    cursor: pointer;
  }

  .notices {
    max-height: 34vh;
    border: 1px solid var(--border-color, #3e3e42);
    border-radius: 3px;
    overflow-y: auto;
  }

  .notice + .notice {
    border-top: 1px solid var(--border-color, #3e3e42);
  }

  .notice-head {
    display: flex;
    gap: 8px;
    align-items: baseline;
    width: 100%;
    padding: 4px 8px;
    border: 0;
    background: transparent;
    color: var(--text-main, #cccccc);
    font: inherit;
    font-size: 12px;
    text-align: left;
    cursor: pointer;
  }

  .notice-head:hover {
    background: var(--surface-hover, rgb(255 255 255 / 8%));
  }

  .name {
    flex: 1 1 auto;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }

  .version,
  .source,
  .spdx {
    flex: 0 0 auto;
    color: var(--text-muted, #808080);
  }

  pre {
    max-height: 30vh;
    margin: 0;
    padding: 6px 8px;
    background: var(--bg-app, #1e1e1e);
    color: var(--text-main, #cccccc);
    font-family: var(--font-mono, monospace);
    font-size: 11px;
    white-space: pre-wrap;
    overflow: auto;
    user-select: text;
  }
</style>
